models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct
    streaming: True
    parameters:
      api_key: "<OPENAI_API_KEY>"
      temperature: 0.1


rails:
  input:
    flows:
      - self check input
